# Generated by Django 5.2.3 on 2025-12-16 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current', null=True)),
                ('bullet_1', models.CharField(help_text='First responsibility/achievement', max_length=500)),
                ('bullet_2', models.CharField(help_text='Second responsibility/achievement', max_length=500)),
                ('bullet_3', models.CharField(help_text='Third responsibility/achievement', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Career Entries',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Auto-calculated from file', null=True)),
                ('audio_file', models.FileField(help_text='Upload .wav or .mp3 file (max 100MB)', upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3'])])),
                ('cover_art', models.ImageField(blank=True, help_text='Album artwork (optional)', null=True, upload_to='music/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('play_count', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Music Tracks',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Profile image (recommended: square, min 400x400px)', upload_to='profile/')),
                ('alt_text', models.CharField(blank=True, help_text="Alt text for accessibility (e.g., 'Eddie at a music studio')", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Include in rotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profile Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text="e.g., 'Tutorial', 'Demo', 'Showcase'", max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('video_file', models.FileField(help_text='Upload .mp4 file (1440p recommended, max 10GB)', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail (auto-generated if not provided)', null=True, upload_to='videos/thumbnails/')),
                ('duration', models.DurationField(blank=True, help_text='Video length', null=True)),
                ('resolution', models.CharField(blank=True, help_text="e.g., '1920x1080', '2560x1440'", max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech_frameworks', 'Technologies and Frameworks'), ('programming_languages', 'Programming Languages'), ('databases', 'Databases'), ('developer_tools', 'Developer Tools')], max_length=25)),
                ('proficiency', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Proficient'), (4, 'Advanced'), (5, 'Expert')], default=3)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', '-proficiency', 'order'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
