# Generated by Django 5.2.3 on 2026-03-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_video_url', models.URLField(blank=True, help_text='URL to a looping video shown when not live')),
                ('next_stream_date', models.DateTimeField(blank=True, help_text='When the next stream is scheduled', null=True)),
                ('next_stream_title', models.CharField(blank=True, help_text='Title/topic for the next stream', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stream Configuration',
                'verbose_name_plural': 'Stream Configuration',
            },
        ),
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('streamed_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('s3_recording_prefix', models.CharField(blank=True, max_length=500)),
                ('vod_playlist_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-streamed_at'],
            },
        ),
    ]
