# Generated by Django 5.2.3 on 2026-03-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_streamconfig_streamsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='view_count',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail override (YouTube provides one automatically)', null=True, upload_to='videos/thumbnails/'),
        ),
    ]
