# Generated by Django 5.2.3 on 2026-03-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_video_resolution_remove_video_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
    ]
