# Generated by Django 5.2.3 on 2026-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='original_image',
            field=models.ImageField(blank=True, help_text='Original unmodified upload for re-cropping', upload_to='profile/originals/'),
        ),
    ]
