# Generated by Django 5.2.3 on 2026-06-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_add_original_image_to_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamChatPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_lower', models.CharField(max_length=50, unique=True)),
                ('username_display', models.CharField(max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamPresenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_start_time', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
